/**
 * Vercel Serverless Function - MCP Endpoint
 *
 * This is the entry point for the MCP server on Vercel.
 * No Next.js, no mcp-handler - just a simple serverless function.
 *
 * Deploy to Vercel and the MCP will be available at /api/mcp
 */

// @ts-ignore - Generated at build time
import { createNotesApp } from "../dist/server/app.js";

// For serverless, we need to bundle the UI HTML
// This is generated by `npm run build:ui` with generateBundle: true
// @ts-ignore - Generated at build time
import { main as bundledHtml } from "../dist/ui/bundle.js";

// Create app with bundled HTML for serverless
const app = createNotesApp({ html: bundledHtml });

// Export the handler for Vercel
export default app.toVercelFunctionHandler();
