/**
 * Vercel Serverless Function - MCP Endpoint
 *
 * This is the entry point for the MCP server on Vercel.
 * Deploy to Vercel and the MCP will be available at /api/mcp
 */

// @ts-ignore - Generated at build time
import { createTodosApp } from "../dist/server/app.js";

// Bundled UI HTML generated by `npm run build:ui` with generateBundle: true
// @ts-ignore - Generated at build time
import { main as bundledHtml } from "../dist/ui/bundle.js";

// Create app with bundled HTML for serverless
const app = createTodosApp({ html: bundledHtml });

// Export the handler for Vercel
export default app.toVercelFunctionHandler();
